// apps/react/src/components/Footer.tsx
import globalCopy from '@packages/assets/copy/global.json'

export default function Footer() {
  const year = new Date().getFullYear()
  return (
    <footer className="c-footer">
      <div className="l-container c-footer__inner">
        <div className="c-footer__legal">{globalCopy.footer.copyright.replace('{year}', String(year))}</div>
        <nav className="c-footer__links" aria-label="Footer">
          <a className="c-footer__link" href="#">{globalCopy.footer.privacy}</a>
          <a className="c-footer__link" href="#">{globalCopy.footer.terms}</a>
          <a className="c-footer__link" href="#">{globalCopy.footer.help}</a>
        </nav>
        <p className="c-footer__note">{globalCopy.footer.note}</p>
      </div>
    </footer>
  )
}

// vue/src/components/Footer.vue
<template>
  <footer class="c-footer">
    <div class="c-footer__inner">
      <div class="c-footer__legal">{{ yearText }}</div>
      <nav class="c-footer__links" aria-label="Footer">
        <a class="c-footer__link" href="#">{{ copy.footer.privacy }}</a>
        <a class="c-footer__link" href="#">{{ copy.footer.terms }}</a>
        <a class="c-footer__link" href="#">{{ copy.footer.help }}</a>
      </nav>
      <p class="c-footer__note">{{ copy.footer.note }}</p>
    </div>
  </footer>
</template>
<script setup lang="ts">
import copy from '../../../packages/assets/copy/global.json'
const yearText = copy.footer.copyright.replace('{year}', String(new Date().getFullYear()))
</script>
