// react/src/components/Header.tsx
import { Link, useLocation } from 'react-router-dom'
import { useEffect, useMemo, useState } from 'react'
import globalCopy from '../../../packages/assets/copy/global.json'

type Theme = 'light' | 'dark'

export default function Header() {
  const location = useLocation()
  const isAuthRoute = location.pathname.startsWith('/auth')
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  const [theme, setTheme] = useState<Theme>(
    document.documentElement.dataset.theme === 'dark' ? 'dark' : 'light'
  )

  useEffect(() => {
    document.documentElement.dataset.theme = theme
  }, [theme])

  const links = useMemo(() => {
    if (isAuthRoute) {
      return [
        { to: '/auth/login', label: globalCopy.nav.login },
        { to: '/auth/signup', label: globalCopy.nav.signup }
      ]
    }
    return [
      { to: '/dashboard', label: globalCopy.nav.dashboard },
      { to: '/tickets', label: globalCopy.nav.tickets },
      { to: '/auth/login', label: globalCopy.nav.logout }
    ]
  }, [isAuthRoute])

  const menuLabel = isMenuOpen ? globalCopy.nav.toggle.close : globalCopy.nav.toggle.open
  const nextTheme = theme === 'light' ? 'Dark' : 'Light'
  const themeToggleLabel = globalCopy.theme.toggle.replace('{app.theme}', nextTheme)

  const toggleTheme = () => {
    setTheme((current) => (current === 'light' ? 'dark' : 'light'))
  }

  return (
    <header className="c-header">
      <div className="c-header__inner">
        <Link to="/" className="c-header__brand">{globalCopy.app.name}</Link>
        <div className="l-cluster">
          <button
            className="c-header__toggle"
            type="button"
            aria-controls="primary-nav"
            aria-expanded={isMenuOpen}
            aria-label={menuLabel}
            onClick={() => setIsMenuOpen((open) => !open)}
          >
            <span className="sr-only">{menuLabel}</span>
          </button>
          <button
            className="c-button c-button--secondary hidden md:inline-flex"
            type="button"
            onClick={toggleTheme}
          >
            {themeToggleLabel}
          </button>
        </div>
        <nav
          id="primary-nav"
          className={`c-header__nav ${isMenuOpen ? 'flex flex-col gap-sm md:flex md:flex-row' : ''}`}
          aria-label="Primary"
          data-state={isMenuOpen ? 'open' : 'closed'}
        >
          {links.map((link) => (
            <Link key={link.to} to={link.to} className="c-header__link">{link.label}</Link>
          ))}
          <button
            className="c-button c-button--secondary md:hidden"
            type="button"
            onClick={toggleTheme}
          >
            {themeToggleLabel}
          </button>
        </nav>
      </div>
    </header>
  )
}

// vue/src/components/Header.vue
<template>
  <header class="c-header">
    <div class="c-header__inner">
      <RouterLink to="/" class="c-header__brand">{{ copy.app.name }}</RouterLink>
      <div class="l-cluster">
        <button
          class="c-header__toggle"
          type="button"
          aria-controls="primary-nav"
          :aria-expanded="isMenuOpen"
          :aria-label="menuLabel"
          @click="toggleMenu"
        >
          <span class="sr-only">{{ menuLabel }}</span>
        </button>
        <button
          class="c-button c-button--secondary hidden md:inline-flex"
          type="button"
          @click="toggleTheme"
        >
          {{ themeToggleLabel }}
        </button>
      </div>
      <nav
        id="primary-nav"
        :class="['c-header__nav', isMenuOpen ? 'flex flex-col gap-sm md:flex md:flex-row' : '']"
        aria-label="Primary"
        :data-state="isMenuOpen ? 'open' : 'closed'"
      >
        <RouterLink
          v-for="link in links"
          :key="link.to"
          :to="link.to"
          class="c-header__link"
        >
          {{ link.label }}
        </RouterLink>
        <button
          class="c-button c-button--secondary md:hidden"
          type="button"
          @click="toggleTheme"
        >
          {{ themeToggleLabel }}
        </button>
      </nav>
    </div>
  </header>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { RouterLink, useRoute } from 'vue-router'
import copy from '../../../packages/assets/copy/global.json'

type Theme = 'light' | 'dark'

const route = useRoute()
const isMenuOpen = ref(false)
const theme = ref<Theme>(document.documentElement.dataset.theme === 'dark' ? 'dark' : 'light')

const isAuthRoute = computed(() => route.path.startsWith('/auth'))
const links = computed(() => {
  if (isAuthRoute.value) {
    return [
      { to: '/auth/login', label: copy.nav.login },
      { to: '/auth/signup', label: copy.nav.signup }
    ]
  }
  return [
    { to: '/dashboard', label: copy.nav.dashboard },
    { to: '/tickets', label: copy.nav.tickets },
    { to: '/auth/login', label: copy.nav.logout }
  ]
})

const menuLabel = computed(() =>
  isMenuOpen.value ? copy.nav.toggle.close : copy.nav.toggle.open
)
const themeToggleLabel = computed(() => {
  const nextTheme = theme.value === 'light' ? 'Dark' : 'Light'
  return copy.theme.toggle.replace('{app.theme}', nextTheme)
})

const toggleMenu = () => {
  isMenuOpen.value = !isMenuOpen.value
}

const toggleTheme = () => {
  theme.value = theme.value === 'light' ? 'dark' : 'light'
  document.documentElement.dataset.theme = theme.value
}

onMounted(() => {
  document.documentElement.dataset.theme = theme.value
})
</script>
