// apps/vue/src/routes/Dashboard.vue
<template>
  <section class="py-2xl l-stack">
    <header class="c-page-header">
      <h1 class="c-page-header__title">{{ copy.title }}</h1>
      <p class="c-page-header__subtitle">{{ copy.subtitle }}</p>
    </header>
    <div class="grid gap-lg md:grid-cols-4" :aria-busy="loading">
      <article
        v-for="stat in stats"
        :key="stat.key"
        class="c-stat-card animate-fade-up"
      >
        <div>
          <span class="c-stat-card__label">{{ stat.label }}</span>
          <div class="c-stat-card__value">{{ stat.value }}</div>
        </div>
      </article>
    </div>
    <div class="c-page-header__actions">
      <RouterLink class="c-button c-button--primary" to="/tickets">
        {{ copy.actions.toTickets }}
      </RouterLink>
    </div>
    <section v-if="!loading && !hasTickets" class="c-empty animate-fade-up">
      <div
        class="c-empty__illustration"
        aria-hidden="true"
        role="presentation"
        v-html="barChart"
      />
      <p class="c-empty__title">{{ ticketsCopy.empty.primary.title }}</p>
      <RouterLink class="c-button c-button--primary" to="/tickets">
        {{ ticketsCopy.empty.primary.action }}
      </RouterLink>
    </section>
  </section>
</template>
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { RouterLink } from 'vue-router'
import copy from '@packages/assets/copy/dashboard.json'
import ticketsCopy from '@packages/assets/copy/tickets.json'
import barChart from '@packages/assets/media/icons/bar-chart.svg?raw'
import { getTicketStats, TICKETS_CHANGED_EVENT } from '@packages/utils/tickets'
import { usePageMeta } from '../composables/usePageMeta'

type StatKey = 'total' | 'open' | 'inProgress' | 'closed'

const totals = reactive<Record<StatKey, number>>({
  total: 0,
  open: 0,
  inProgress: 0,
  closed: 0
})

const loading = ref(true)

usePageMeta({
  title: copy.title,
  description: copy.subtitle
})

const stats = computed(() => ([
  { key: 'total', label: copy.stats.total, value: totals.total },
  { key: 'open', label: copy.stats.open, value: totals.open },
  { key: 'inProgress', label: copy.stats.inProgress, value: totals.inProgress },
  { key: 'closed', label: copy.stats.closed, value: totals.closed }
]))

const hasTickets = computed(() => totals.total > 0)

const loadStats = async () => {
  loading.value = true
  try {
    const data = await getTicketStats()
    totals.total = data.total
    totals.open = data.open
    totals.inProgress = data.inProgress
    totals.closed = data.closed
  } finally {
    loading.value = false
  }
}

const handleTicketsChanged = () => {
  loadStats()
}

onMounted(() => {
  loadStats()
  window.addEventListener(TICKETS_CHANGED_EVENT, handleTicketsChanged)
})

onBeforeUnmount(() => {
  window.removeEventListener(TICKETS_CHANGED_EVENT, handleTicketsChanged)
})
</script>

// apps/react/src/routes/Dashboard.tsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import copy from '@packages/assets/copy/dashboard.json'
import ticketsCopy from '@packages/assets/copy/tickets.json'
import barChart from '@packages/assets/media/icons/bar-chart.svg?raw'
import { getTicketStats, TICKETS_CHANGED_EVENT } from '@packages/utils/tickets'
import { useAuthGuard } from '../hooks/useAuthGuard'
import { usePageMeta } from '../hooks/usePageMeta'

type StatKey = 'total' | 'open' | 'inProgress' | 'closed'

export default function Dashboard() {
  useAuthGuard()
  usePageMeta({ title: copy.title, description: copy.subtitle })
  const [stats, setStats] = useState<Record<StatKey, number>>({
    total: 0,
    open: 0,
    inProgress: 0,
    closed: 0
  })
  const [loading, setLoading] = useState(true)

  const statEntries = useMemo(
    () => [
      { key: 'total', label: copy.stats.total, value: stats.total },
      { key: 'open', label: copy.stats.open, value: stats.open },
      { key: 'inProgress', label: copy.stats.inProgress, value: stats.inProgress },
      { key: 'closed', label: copy.stats.closed, value: stats.closed }
    ],
    [stats]
  )

  const hasTickets = stats.total > 0

  const loadStats = useCallback(async () => {
    setLoading(true)
    const data = await getTicketStats()
    setStats(data)
    setLoading(false)
  }, [])

  useEffect(() => {
    loadStats()
    const handler = () => loadStats()
    window.addEventListener(TICKETS_CHANGED_EVENT, handler)
    return () => {
      window.removeEventListener(TICKETS_CHANGED_EVENT, handler)
    }
  }, [loadStats])

  return (
    <section className="py-2xl l-stack">
      <header className="c-page-header">
        <h1 className="c-page-header__title">{copy.title}</h1>
        <p className="c-page-header__subtitle">{copy.subtitle}</p>
      </header>
      <div className="grid gap-lg md:grid-cols-4" aria-busy={loading}>
        {statEntries.map((stat) => (
          <article className="c-stat-card animate-fade-up" key={stat.key}>
            <div>
              <span className="c-stat-card__label">{stat.label}</span>
              <div className="c-stat-card__value">{stat.value}</div>
            </div>
          </article>
        ))}
      </div>
      <div className="c-page-header__actions">
        <Link className="c-button c-button--primary" to="/tickets">{copy.actions.toTickets}</Link>
      </div>
      {!loading && !hasTickets && (
        <section className="c-empty animate-fade-up">
          <div
            className="c-empty__illustration"
            aria-hidden="true"
            role="presentation"
            dangerouslySetInnerHTML={{ __html: barChart }}
          />
          <p className="c-empty__title">{ticketsCopy.empty.primary.title}</p>
          <Link className="c-button c-button--primary" to="/tickets">
            {ticketsCopy.empty.primary.action}
          </Link>
        </section>
      )}
    </section>
  )
}
