// vue/src/App.vue
<script setup lang="ts">
import Header from './components/Header.vue'
import Footer from './components/Footer.vue'
import Toast from './components/Toast.vue'
import globalCopy from '@packages/assets/copy/global.json'

import '@packages/styles/app.css'
</script>
<template>
  <a href="#main-content" class="c-skiplink">{{ globalCopy.a11y.skipLink }}</a>
  <Header />
  <main id="main-content" class="l-page">
    <div class="l-container">
      <router-view />
    </div>
  </main>
  <Footer />
  <Toast />
</template>

// react/src/App.tsx
import Header from './components/Header'
import Footer from './components/Footer'
import Toast from './components/Toast'
import globalCopy from '@packages/assets/copy/global.json'
import '@packages/styles/app.css'

export default function App({ children }: { children: React.ReactNode }) {
  return (
    <>
      <a href="#main-content" className="c-skiplink">{globalCopy.a11y.skipLink}</a>
      <Header />
      <main id="main-content" className="l-page">
        <div className="l-container">{children}</div>
      </main>
      <Footer />
      <Toast />
    </>
  )
}
