// apps/react/src/components/Header.tsx
import { Link, useNavigate } from 'react-router-dom'
import { useEffect, useMemo, useState } from 'react'
import globalCopy from '@packages/assets/copy/global.json'
import { getStoredTheme, persistTheme, toggleTheme, type Theme } from '@packages/utils/theme'
import { logout } from '@packages/utils/auth'
import { pushToast } from '@packages/utils/toast'
import { useSession } from '../hooks/useSession'

export default function Header() {
  const navigate = useNavigate()
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  const [theme, setTheme] = useState<Theme>(getStoredTheme())
  const session = useSession()
  const isAuthenticated = Boolean(session)

  useEffect(() => {
    persistTheme(theme)
  }, [theme])

  const links = useMemo(() => {
    if (isAuthenticated) {
      return [
        { to: '/dashboard', label: globalCopy.nav.dashboard },
        { to: '/tickets', label: globalCopy.nav.tickets },
        { to: '/auth/login', label: globalCopy.nav.logout, action: 'logout' as const }
      ]
    }
    return [
      { to: '/auth/signup', label: globalCopy.nav.signup },
      { to: '/auth/login', label: globalCopy.nav.login }
    ]
  }, [isAuthenticated])

  const menuLabel = isMenuOpen ? globalCopy.nav.toggle.close : globalCopy.nav.toggle.open
  const nextTheme = theme === 'light' ? 'Dark' : 'Light'
  const themeToggleLabel = globalCopy.theme.toggle.replace('{app.theme}', nextTheme)

  const handleThemeToggle = () => {
    setTheme((current) => toggleTheme(current))
  }

  const handleNavigate = () => {
    setIsMenuOpen(false)
  }

  const handleLogout = () => {
    logout()
    setIsMenuOpen(false)
    pushToast(globalCopy.toasts.authEnd, 'info')
    navigate('/', { replace: true })
  }

  return (
    <header className="c-header">
      <div className="c-header__inner">
        <div className='l-cluster justify-between w-full'>
          <Link to="/" className="c-header__brand">{globalCopy.app.name}</Link>
          <div className="l-cluster">
            <button
              className="c-header__toggle"
              type="button"
              aria-controls="primary-nav"
              aria-expanded={isMenuOpen}
              aria-label={menuLabel}
              onClick={() => setIsMenuOpen((open) => !open)}
              data-state={isMenuOpen ? 'open' : 'closed'}
            >
              <span className="sr-only">{menuLabel}</span>
              <span className="c-header__toggle-icon" aria-hidden="true" />
            </button>
          </div>
        </div>
        <nav
          id="primary-nav"
          className={`c-header__nav ${isMenuOpen ? 'flex flex-col gap-sm md:flex md:flex-row' : ''}`}
          aria-label="Primary"
          data-state={isMenuOpen ? 'open' : 'closed'}
        >
          {links.map((link) => (
            link.action === 'logout' ? (
              <button key={link.label} className="c-header__link" type="button" onClick={handleLogout}>
                {link.label}
              </button>
            ) : (
              <Link key={link.to} to={link.to} className="c-header__link" onClick={handleNavigate}>{link.label}</Link>
            )
          ))}
          <button
            className="c-button c-button--secondary"
            type="button"
            onClick={handleThemeToggle}
          >
            {themeToggleLabel}
          </button>
        </nav>
      </div>
    </header>
  )
}

// apps/vue/src/components/Header.vue
<template>
  <header class="c-header">
    <div class="c-header__inner">
      <div class="l-cluster justify-between w-full">
        <RouterLink to="/" class="c-header__brand">{{ copy.app.name }}</RouterLink>
        <div class="l-cluster">
          <button
            class="c-header__toggle"
            type="button"
            aria-controls="primary-nav"
            :aria-expanded="isMenuOpen"
            :aria-label="menuLabel"
            @click="toggleMenu"
            :data-state="isMenuOpen ? 'open' : 'closed'"
          >
            <span class="sr-only">{{ menuLabel }}</span>
            <span class="c-header__toggle-icon" aria-hidden="true"></span>
          </button>
        </div>
      </div>
      <nav
        id="primary-nav"
        :class="['c-header__nav', isMenuOpen ? 'flex flex-col gap-sm md:flex md:flex-row' : '']"
        aria-label="Primary"
        :data-state="isMenuOpen ? 'open' : 'closed'"
      >
        <template v-for="link in links" :key="link.label">
          <RouterLink
            v-if="link.action !== 'logout'"
            :to="link.to"
            class="c-header__link"
            @click="handleNavigate"
          >
            {{ link.label }}
          </RouterLink>
          <button
            v-else
            type="button"
            class="c-header__link"
            @click="handleLogout"
          >
            {{ link.label }}
          </button>
        </template>
        <button
          class="c-button c-button--secondary"
          type="button"
          @click="toggleThemeHandler"
        >
          {{ themeToggleLabel }}
        </button>
      </nav>
    </div>
  </header>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { RouterLink, useRouter } from 'vue-router'
import copy from '@packages/assets/copy/global.json'
import { getStoredTheme, persistTheme, toggleTheme, type Theme } from '@packages/utils/theme'
import { logout } from '@packages/utils/auth'
import { pushToast } from '@packages/utils/toast'
import { useSession } from '../composables/useSession'

const router = useRouter()
const isMenuOpen = ref(false)
const theme = ref<Theme>(getStoredTheme())
const session = useSession()
const isAuthenticated = computed(() => !!session.value)
const links = computed(() => {
  if (isAuthenticated.value) {
    return [
      { to: '/dashboard', label: copy.nav.dashboard },
      { to: '/tickets', label: copy.nav.tickets },
      { to: '/auth/login', label: copy.nav.logout, action: 'logout' as const }
    ]
  }
  return [
    { to: '/auth/signup', label: copy.nav.signup },
    { to: '/auth/login', label: copy.nav.login }
  ]
})

const menuLabel = computed(() =>
  isMenuOpen.value ? copy.nav.toggle.close : copy.nav.toggle.open
)
const themeToggleLabel = computed(() => {
  const nextTheme = theme.value === 'light' ? 'Dark' : 'Light'
  return copy.theme.toggle.replace('{app.theme}', nextTheme)
})

const toggleMenu = () => {
  isMenuOpen.value = !isMenuOpen.value
}

const toggleThemeHandler = () => {
  theme.value = toggleTheme(theme.value)
  persistTheme(theme.value)
}

const handleNavigate = () => {
  isMenuOpen.value = false
}

const handleLogout = async () => {
  logout()
  isMenuOpen.value = false
  pushToast(copy.toasts.authEnd ?? 'Session ended, please login again to continue.', 'info')
  await router.push('/')
}

onMounted(() => {
  persistTheme(theme.value)
})
</script>
