// react/src/routes/Dashboard.tsx
import { Link } from 'react-router-dom'
import copy from '../../../packages/assets/copy/dashboard.json'
import ticketsCopy from '../../../packages/assets/copy/tickets.json'
import barChart from '../../../packages/assets/media/icons/bar-chart.svg'

const totals = {
  total: 0,
  open: 0,
  inProgress: 0,
  closed: 0
}

export default function Dashboard() {
  const stats = [
    { key: 'total', label: copy.stats.total, value: totals.total },
    { key: 'open', label: copy.stats.open, value: totals.open },
    { key: 'inProgress', label: copy.stats.inProgress, value: totals.inProgress },
    { key: 'closed', label: copy.stats.closed, value: totals.closed }
  ]
  const hasTickets = totals.total > 0

  return (
    <section className="l-container py-2xl l-stack">
      <header className="c-page-header">
        <h1 className="c-page-header__title">{copy.title}</h1>
        <p className="c-page-header__subtitle">{copy.subtitle}</p>
      </header>
      <div className="grid gap-lg md:grid-cols-4">
        {stats.map((stat) => (
          <article className="c-stat-card" key={stat.key}>
            <div>
              <span className="c-stat-card__label">{stat.label}</span>
              <div className="c-stat-card__value">{stat.value}</div>
            </div>
          </article>
        ))}
      </div>
      <div className="c-page-header__actions">
        <Link className="c-button c-button--primary" to="/tickets">{copy.actions.toTickets}</Link>
      </div>
      {!hasTickets && (
        <section className="c-empty">
          <img className="c-empty__illustration" src={barChart} alt="" />
          <p className="c-empty__title">{ticketsCopy.empty.primary.title}</p>
          <Link className="c-button c-button--primary" to="/tickets">
            {ticketsCopy.empty.primary.action}
          </Link>
        </section>
      )}
    </section>
  )
}

// vue/src/routes/Dashboard.vue
<template>
  <section class="l-container py-2xl l-stack">
    <header class="c-page-header">
      <h1 class="c-page-header__title">{{ copy.title }}</h1>
      <p class="c-page-header__subtitle">{{ copy.subtitle }}</p>
    </header>
    <div class="grid gap-lg md:grid-cols-4">
      <article
        v-for="stat in stats"
        :key="stat.key"
        class="c-stat-card"
      >
        <div>
          <span class="c-stat-card__label">{{ stat.label }}</span>
          <div class="c-stat-card__value">{{ stat.value }}</div>
        </div>
      </article>
    </div>
    <div class="c-page-header__actions">
      <RouterLink class="c-button c-button--primary" to="/tickets">
        {{ copy.actions.toTickets }}
      </RouterLink>
    </div>
    <section v-if="!hasTickets" class="c-empty">
      <img class="c-empty__illustration" :src="barChart" alt="" />
      <p class="c-empty__title">{{ ticketsCopy.empty.primary.title }}</p>
      <RouterLink class="c-button c-button--primary" to="/tickets">
        {{ ticketsCopy.empty.primary.action }}
      </RouterLink>
    </section>
  </section>
</template>
<script setup lang="ts">
import { computed } from 'vue'
import { RouterLink } from 'vue-router'
import copy from '../../../packages/assets/copy/dashboard.json'
import ticketsCopy from '../../../packages/assets/copy/tickets.json'
import barChart from '../../../packages/assets/media/icons/bar-chart.svg'

type StatKey = 'total' | 'open' | 'inProgress' | 'closed'

const totals: Record<StatKey, number> = {
  total: 0,
  open: 0,
  inProgress: 0,
  closed: 0
}

const stats = computed(() => ([
  { key: 'total', label: copy.stats.total, value: totals.total },
  { key: 'open', label: copy.stats.open, value: totals.open },
  { key: 'inProgress', label: copy.stats.inProgress, value: totals.inProgress },
  { key: 'closed', label: copy.stats.closed, value: totals.closed }
]))

const hasTickets = computed(() => totals.total > 0)
</script>
