// vue/src/components/TicketModal.vue
<template>
  <teleport to="body">
    <div v-if="visible" class="c-modal" role="dialog" aria-modal="true" @click="emitClose">
      <div class="c-modal__panel" @click.stop>
        <header class="l-stack">
          <h2 class="c-modal__title">{{ heading }}</h2>
        </header>
        <form class="l-stack" @submit.prevent="handleSubmit">
          <div class="c-field">
            <label for="modal-title" class="c-field__label">{{ ticketsCopy.form.labels.title }}</label>
            <input
              id="modal-title"
              v-model="draft.title"
              :placeholder="ticketsCopy.form.placeholders.title"
              class="c-field__control"
            />
            <p v-if="errors.title" class="c-field__message">{{ errors.title }}</p>
          </div>
          <div class="c-field">
            <label for="modal-description" class="c-field__label">{{ ticketsCopy.form.labels.description }}</label>
            <textarea
              id="modal-description"
              v-model="draft.description"
              :placeholder="ticketsCopy.form.placeholders.description"
              rows="5"
              class="c-field__control"
            ></textarea>
          </div>
          <div class="grid gap-sm md:grid-cols-2">
            <div class="c-field">
              <label for="modal-status" class="c-field__label">{{ ticketsCopy.form.labels.status }}</label>
              <select id="modal-status" v-model="draft.status" class="c-field__control">
                <option v-for="status in statusOptions" :key="status" :value="status">
                  {{ formatStatus(status) }}
                </option>
              </select>
              <p v-if="errors.status" class="c-field__message">{{ errors.status }}</p>
            </div>
            <div class="c-field">
              <label for="modal-priority" class="c-field__label">{{ ticketsCopy.form.labels.priority }}</label>
              <select id="modal-priority" v-model="draft.priority" class="c-field__control">
                <option v-for="priority in priorityOptions" :key="priority" :value="priority">
                  {{ formatPriority(priority) }}
                </option>
              </select>
              <p v-if="errors.priority" class="c-field__message">{{ errors.priority }}</p>
            </div>
          </div>
          <div class="c-modal__actions">
            <button type="button" class="c-button c-button--secondary" @click="emitClose">
              {{ ticketsCopy.form.actions.cancel }}
            </button>
            <button type="submit" class="c-button c-button--primary">
              {{ actionLabel }}
            </button>
          </div>
        </form>
      </div>
    </div>
  </teleport>
</template>
<script setup lang="ts">
import { computed, reactive, watch } from 'vue'
import ticketsCopy from '../../../packages/assets/copy/tickets.json'
import globalCopy from '../../../packages/assets/copy/global.json'
import type { Ticket, TicketDraft, TicketPriority, TicketStatus } from '../../../packages/utils/tickets'

type ModalMode = 'create' | 'edit'

const props = defineProps<{
  visible: boolean
  mode: ModalMode
  ticket?: Ticket | null
}>()

const emit = defineEmits<{
  (e: 'close'): void
  (e: 'submit', payload: TicketDraft): void
}>()

const defaultDraft = (): TicketDraft => ({
  title: '',
  description: '',
  status: 'open',
  priority: 'medium'
})

const draft = reactive<TicketDraft>(defaultDraft())
const errors = reactive<{ title: string; status: string; priority: string }>({
  title: '',
  status: '',
  priority: ''
})

const statusOptions = ticketsCopy.card.statusTags as TicketStatus[]
const priorityOptions = ticketsCopy.card.priorityTags as TicketPriority[]

const heading = computed(() =>
  props.mode === 'edit' ? ticketsCopy.form.actions.update : ticketsCopy.actions.new
)

const actionLabel = computed(() =>
  props.mode === 'edit' ? ticketsCopy.form.actions.update : ticketsCopy.form.actions.save
)

const hydrate = (ticket?: Ticket | null) => {
  const source = ticket
    ? {
        title: ticket.title,
        description: ticket.description,
        status: ticket.status,
        priority: ticket.priority
      }
    : defaultDraft()

  draft.title = source.title
  draft.description = source.description
  draft.status = source.status
  draft.priority = source.priority
  errors.title = ''
  errors.status = ''
  errors.priority = ''
}

watch(
  () => props.visible,
  (visible) => {
    if (visible) {
      hydrate(props.mode === 'edit' ? props.ticket ?? null : null)
    }
  }
)

watch(
  () => props.ticket,
  (ticket) => {
    if (props.visible && props.mode === 'edit') {
      hydrate(ticket ?? null)
    }
  },
  { immediate: true }
)

const validate = () => {
  errors.title = draft.title.trim() ? '' : globalCopy.validation.titleRequired
  errors.status = draft.status ? '' : globalCopy.validation.statusRequired
  errors.priority = draft.priority ? '' : globalCopy.validation.priorityRequired
  return !errors.title && !errors.status && !errors.priority
}

const emitClose = () => emit('close')

const handleSubmit = () => {
  if (!validate()) return
  emit('submit', {
    title: draft.title.trim(),
    description: draft.description.trim(),
    status: draft.status,
    priority: draft.priority
  })
}

const formatStatus = (status: TicketStatus) => status.replace('_', ' ')
const formatPriority = (priority: TicketPriority) =>
  priority.charAt(0).toUpperCase() + priority.slice(1)
</script>

// react/src/components/TicketModal.tsx
import { FormEvent, MouseEvent, useEffect, useMemo, useState } from 'react'
import { createPortal } from 'react-dom'
import ticketsCopy from '../../../packages/assets/copy/tickets.json'
import globalCopy from '../../../packages/assets/copy/global.json'
import type { Ticket, TicketDraft, TicketPriority, TicketStatus } from '../../../packages/utils/tickets'

type ModalMode = 'create' | 'edit'

type Props = {
  visible: boolean
  mode: ModalMode
  ticket?: Ticket | null
  onClose: () => void
  onSubmit: (draft: TicketDraft) => void
}

const statusOptions = ticketsCopy.card.statusTags as TicketStatus[]
const priorityOptions = ticketsCopy.card.priorityTags as TicketPriority[]

const defaultDraft = (): TicketDraft => ({
  title: '',
  description: '',
  status: 'open',
  priority: 'medium'
})

export default function TicketModal({ visible, mode, ticket, onClose, onSubmit }: Props) {
const [draft, setDraft] = useState<TicketDraft>(() => defaultDraft())
  const [errors, setErrors] = useState({ title: '', status: '', priority: '' })

  useEffect(() => {
    if (!visible) return
    if (mode === 'edit' && ticket) {
      setDraft({
        title: ticket.title,
        description: ticket.description,
        status: ticket.status,
        priority: ticket.priority
      })
    } else {
      setDraft(defaultDraft())
    }
    setErrors({ title: '', status: '', priority: '' })
  }, [visible, mode, ticket])

  const heading = useMemo(
    () => (mode === 'edit' ? ticketsCopy.form.actions.update : ticketsCopy.actions.new),
    [mode]
  )

  const actionLabel = useMemo(
    () => (mode === 'edit' ? ticketsCopy.form.actions.update : ticketsCopy.form.actions.save),
    [mode]
  )

  if (!visible || typeof document === 'undefined') {
    return null
  }

  const validate = () => {
    const nextErrors = {
      title: draft.title.trim() ? '' : globalCopy.validation.titleRequired,
      status: draft.status ? '' : globalCopy.validation.statusRequired,
      priority: draft.priority ? '' : globalCopy.validation.priorityRequired
    }
    setErrors(nextErrors)
    return !nextErrors.title && !nextErrors.status && !nextErrors.priority
  }

  const handleSubmit = (event: FormEvent) => {
    event.preventDefault()
    if (!validate()) return
    onSubmit({
      title: draft.title.trim(),
      description: draft.description.trim(),
      status: draft.status,
      priority: draft.priority
    })
  }

  const overlayClick = (event: MouseEvent<HTMLDivElement>) => {
    if (event.target === event.currentTarget) {
      onClose()
    }
  }

  return createPortal(
    <div className="c-modal" role="dialog" aria-modal="true" onClick={overlayClick}>
      <div className="c-modal__panel" onClick={(event) => event.stopPropagation()}>
        <header className="l-stack">
          <h2 className="c-modal__title">{heading}</h2>
        </header>
        <form className="l-stack" onSubmit={handleSubmit}>
          <div className="c-field">
            <label htmlFor="modal-title" className="c-field__label">{ticketsCopy.form.labels.title}</label>
            <input
              id="modal-title"
              value={draft.title}
              onChange={(event) => setDraft((prev) => ({ ...prev, title: event.target.value }))}
              placeholder={ticketsCopy.form.placeholders.title}
              className="c-field__control"
            />
            {errors.title && <p className="c-field__message">{errors.title}</p>}
          </div>
          <div className="c-field">
            <label htmlFor="modal-description" className="c-field__label">{ticketsCopy.form.labels.description}</label>
            <textarea
              id="modal-description"
              value={draft.description}
              onChange={(event) => setDraft((prev) => ({ ...prev, description: event.target.value }))}
              placeholder={ticketsCopy.form.placeholders.description}
              rows={5}
              className="c-field__control"
            ></textarea>
          </div>
          <div className="grid gap-sm md:grid-cols-2">
            <div className="c-field">
              <label htmlFor="modal-status" className="c-field__label">{ticketsCopy.form.labels.status}</label>
              <select
                id="modal-status"
                value={draft.status}
                onChange={(event) =>
                  setDraft((prev) => ({ ...prev, status: event.target.value as TicketStatus }))
                }
                className="c-field__control"
              >
                {statusOptions.map((status) => (
                  <option key={status} value={status}>{status.replace('_', ' ')}</option>
                ))}
              </select>
              {errors.status && <p className="c-field__message">{errors.status}</p>}
            </div>
            <div className="c-field">
              <label htmlFor="modal-priority" className="c-field__label">{ticketsCopy.form.labels.priority}</label>
              <select
                id="modal-priority"
                value={draft.priority}
                onChange={(event) =>
                  setDraft((prev) => ({ ...prev, priority: event.target.value as TicketPriority }))
                }
                className="c-field__control"
              >
                {priorityOptions.map((priority) => (
                  <option key={priority} value={priority}>
                    {priority.charAt(0).toUpperCase() + priority.slice(1)}
                  </option>
                ))}
              </select>
              {errors.priority && <p className="c-field__message">{errors.priority}</p>}
            </div>
          </div>
          <div className="c-modal__actions">
            <button type="button" className="c-button c-button--secondary" onClick={onClose}>
              {ticketsCopy.form.actions.cancel}
            </button>
            <button type="submit" className="c-button c-button--primary">
              {actionLabel}
            </button>
          </div>
        </form>
      </div>
    </div>,
    document.body
  )
}
