// vue/src/routes/Landing.vue
<script setup lang="ts">
  import { RouterLink } from 'vue-router'
  import copy from '../../../packages/assets/copy/landing.json'
  import circle from '../../../packages/assets/media/circle-1.svg';
  import wave from '../../../packages/assets/media/wave.svg';

  const asset = (icon: string) => {
    return new URL(`../../../packages/assets/media/${icon}`, import.meta.url).toString()
  }
</script>
<template>
  <section class="c-hero">
    <div class="c-hero__inner">
      <h1 class="c-hero__title">{{ copy.hero.title }}</h1>
      <p class="c-hero__subtitle">{{ copy.hero.subtitle }}</p>
      <div class="c-hero__actions">
        <RouterLink to="/auth/signup" class="c-button c-button--primary">{{ copy.hero.primaryCta }}</RouterLink>
        <RouterLink to="/auth/login" class="c-button c-button--secondary">{{ copy.hero.secondaryCta }}</RouterLink>
      </div>
    </div>
    <img :src="wave" class="c-hero__wave" alt="" />
    <img :src="circle" class="c-hero__decor" alt="" />
  </section>

  <section class="l-stack py-2xl">
    <div class="l-grid-3">
      <article v-for="(f, i) in copy.features" :key="i" class="c-feature-card">
        <img :src="asset(f.icon)" class="c-feature-card__icon" alt="" />
        <h3 class="c-feature-card__title">{{ f.title }}</h3>
        <p class="c-feature-card__body">{{ f.body }}</p>
      </article>
    </div>
  </section>

  <section class="l-stack py-2xl">
    <div class="l-grid-3">
      <article v-for="(s, i) in copy.howItWorks" :key="i" class="c-how-step">
        <h3 class="c-how-step__title">{{ s.title }}</h3>
        <p class="c-how-step__body">{{ s.body }}</p>
      </article>
    </div>
  </section>
</template>

// react/src/routes/Landing.tsx
import { Link } from 'react-router-dom'
import landing from '../../../packages/assets/copy/landing.json'
import wave from '../../../packages/assets/media/wave.svg'
import circle from '../../../packages/assets/media/circle-1.svg'

export default function Landing() {
  const asset = (icon: string) =>
    new URL(`../../../packages/assets/media/${icon}`, import.meta.url).toString()
  return (
    <>
      <section className="c-hero">
        <div className="c-hero__inner">
          <h1 className="c-hero__title">{landing.hero.title}</h1>
          <p className="c-hero__subtitle">{landing.hero.subtitle}</p>
          <div className="c-hero__actions">
            <Link to="/auth/signup" className="c-button c-button--primary">{landing.hero.primaryCta}</Link>
            <Link to="/auth/login" className="c-button c-button--secondary">{landing.hero.secondaryCta}</Link>
          </div>
        </div>
        <img src={wave} className="c-hero__wave" alt="" />
        <img src={circle} className="c-hero__decor" alt="" />
      </section>

      <section className="l-stack py-2xl">
        <div className="l-grid-3">
          {landing.features.map((f, i) => (
            <article className="c-feature-card" key={i}>
              <img src={asset(f.icon)} className="c-feature-card__icon" alt="" />
              <h3 className="c-feature-card__title">{f.title}</h3>
              <p className="c-feature-card__body">{f.body}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="l-stack py-2xl">
        <div className="l-grid-3">
          {landing.howItWorks.map((s, i) => (
            <article className="c-how-step" key={i}>
              <h3 className="c-how-step__title">{s.title}</h3>
              <p className="c-how-step__body">{s.body}</p>
            </article>
          ))}
        </div>
      </section>
    </>
  )
}
